line-length = 100
[lint]
select = ["F","E","W","UP","RUF","TRY","FURB"]
ignore = ["E701"]

[lint.per-file-ignores]
"tests/test_overall.py" = ["F401"] # ignore unused imports -> needed for testing
"tests/test_example.py" = ["F401"] # TODO: remove test_example

[format]
