line-length = 100
[lint]
select = ["F","E","W","UP","RUF","TRY","FURB","PL","PGH","PERF","N","I","FLY","TC","SIM"]
ignore = ["E701","PLR2004","PLR0917","PLR0913","PLR0915","PLR0912"]

[lint.per-file-ignores]
"tests/test_overall.py" = ["F401","PLC0415"] # ignore unused imports -> needed for testing
"tests/test_example.py" = ["F401","PLC0415"] # TODO: remove test_example
"tests/*" = ["D"]

[format]
